import type { Entity, Event, Job } from './supabase';

export const MOCK_ENTITIES: Entity[] = [
  {
    id: '1',
    type: 'startup',
    name: 'Talkwalker',
    slug: 'talkwalker',
    tagline: 'AI-powered consumer intelligence platform',
    description: 'Talkwalker is a social media analytics and monitoring platform used by 2,500+ brands worldwide to measure and optimize their digital impact.',
    logo_url: undefined,
    website: 'https://talkwalker.com',
    founded_year: 2009,
    city: 'Luxembourg City',
    lat: 49.6116,
    lng: 6.1319,
    linkedin_url: 'https://linkedin.com/company/talkwalker',
    visible: true,
    featured: true,
    claimed: true,
    created_at: '2024-01-01',
    startup_details: { entity_id: '1', sector: 'AI / ML', stage: 'growth', total_funding: 9800000, employee_range: '201-500', b2b: true, b2c: false },
  },
  {
    id: '2',
    type: 'startup',
    name: 'LuxAI',
    slug: 'luxai',
    tagline: 'Social robots for education and healthcare',
    description: 'LuxAI creates QTrobot, the world\'s first commercially available social robot designed to help children with autism and support elderly care.',
    website: 'https://luxai.com',
    founded_year: 2016,
    city: 'Luxembourg City',
    lat: 49.6200,
    lng: 6.1400,
    visible: true,
    featured: true,
    claimed: false,
    created_at: '2024-01-01',
    startup_details: { entity_id: '2', sector: 'AI / ML', stage: 'series-a', total_funding: 3200000, employee_range: '11-50', b2b: true, b2c: false },
  },
  {
    id: '3',
    type: 'startup',
    name: 'Klaxit',
    slug: 'klaxit',
    tagline: 'Carpooling platform for daily commuters',
    description: 'Klaxit connects employees for daily carpooling to work, reducing congestion and carbon footprint across Luxembourg and beyond.',
    website: 'https://klaxit.com',
    founded_year: 2016,
    city: 'Luxembourg City',
    lat: 49.6050,
    lng: 6.1200,
    visible: true,
    featured: false,
    claimed: false,
    created_at: '2024-01-01',
    startup_details: { entity_id: '3', sector: 'Logistics', stage: 'series-b', total_funding: 14000000, employee_range: '51-200', b2b: true, b2c: true },
  },
  {
    id: '4',
    type: 'startup',
    name: 'Birdlink',
    slug: 'birdlink',
    tagline: 'B2B marketplace for sustainable sourcing',
    description: 'Birdlink is an e-procurement platform helping companies in Luxembourg and the Greater Region find verified, sustainable suppliers.',
    founded_year: 2021,
    city: 'Esch-sur-Alzette',
    lat: 49.4964,
    lng: 5.9806,
    visible: true,
    featured: false,
    claimed: false,
    created_at: '2024-01-01',
    startup_details: { entity_id: '4', sector: 'SaaS', stage: 'seed', total_funding: 800000, employee_range: '1-10', b2b: true, b2c: false },
  },
  {
    id: '5',
    type: 'startup',
    name: 'Payconiq',
    slug: 'payconiq',
    tagline: 'Mobile payment app for Luxembourg & Benelux',
    description: 'Payconiq by Bancontact is the leading mobile payment solution in Luxembourg, enabling instant payments at point of sale, online and peer-to-peer.',
    website: 'https://payconiq.com',
    founded_year: 2014,
    city: 'Luxembourg City',
    lat: 49.6130,
    lng: 6.1320,
    visible: true,
    featured: true,
    claimed: false,
    created_at: '2024-01-01',
    startup_details: { entity_id: '5', sector: 'Fintech', stage: 'growth', total_funding: 45000000, employee_range: '51-200', b2b: true, b2c: true },
  },
  {
    id: '6',
    type: 'startup',
    name: 'SnT Spin-off: Nuage Networks',
    slug: 'nuage-networks',
    tagline: 'Software-defined networking for cloud operators',
    description: 'Nuage Networks emerged from research at the University of Luxembourg SnT, delivering automated SD-WAN and cloud networking solutions.',
    founded_year: 2012,
    city: 'Luxembourg City',
    lat: 49.6240,
    lng: 6.1580,
    visible: true,
    featured: false,
    claimed: false,
    created_at: '2024-01-01',
    startup_details: { entity_id: '6', sector: 'SaaS', stage: 'acquired', total_funding: 0, employee_range: '51-200', b2b: true, b2c: false },
  },
  {
    id: '7',
    type: 'investor',
    name: 'Mangrove Capital Partners',
    slug: 'mangrove-capital-partners',
    tagline: 'Early-stage VC backing European founders',
    description: 'Mangrove Capital Partners is a Luxembourg-based venture capital firm specialising in early-stage technology companies. Known for early investments in Skype and Wix.',
    website: 'https://mangrove.vc',
    founded_year: 2000,
    city: 'Luxembourg City',
    lat: 49.6118,
    lng: 6.1300,
    linkedin_url: 'https://linkedin.com/company/mangrove-capital-partners',
    visible: true,
    featured: true,
    claimed: false,
    created_at: '2024-01-01',
    investor_details: { entity_id: '7', investor_type: 'vc', focus_sectors: ['SaaS', 'Fintech', 'AI / ML', 'E-commerce'], ticket_min: 500000, ticket_max: 5000000, stage_focus: ['pre-seed', 'seed', 'series-a'], portfolio_count: 90 },
  },
  {
    id: '8',
    type: 'investor',
    name: 'Expon Capital',
    slug: 'expon-capital',
    tagline: 'Deep tech VC investing in exponential technologies',
    description: 'Expon Capital focuses on deep tech startups with exponential growth potential, with a strong presence in Luxembourg and the Greater Region.',
    website: 'https://expon.capital',
    founded_year: 2016,
    city: 'Luxembourg City',
    lat: 49.6150,
    lng: 6.1350,
    visible: true,
    featured: true,
    claimed: false,
    created_at: '2024-01-01',
    investor_details: { entity_id: '8', investor_type: 'vc', focus_sectors: ['AI / ML', 'Cybersecurity', 'Space Tech', 'Cleantech'], ticket_min: 250000, ticket_max: 3000000, stage_focus: ['seed', 'series-a'], portfolio_count: 35 },
  },
  {
    id: '9',
    type: 'investor',
    name: 'Luxembourg Future Fund',
    slug: 'luxembourg-future-fund',
    tagline: 'Government-backed fund supporting innovation',
    description: 'The Luxembourg Future Fund is a public-private fund-of-funds managed by the SNCI and EIF, investing in VC funds and innovative companies in Luxembourg.',
    website: 'https://lff.lu',
    founded_year: 2015,
    city: 'Luxembourg City',
    lat: 49.6080,
    lng: 6.1280,
    visible: true,
    featured: false,
    claimed: false,
    created_at: '2024-01-01',
    investor_details: { entity_id: '9', investor_type: 'government', focus_sectors: ['Fintech', 'Logistics', 'Space Tech', 'Cleantech'], ticket_min: 1000000, ticket_max: 20000000, stage_focus: ['seed', 'series-a', 'series-b'], portfolio_count: 22 },
  },
  {
    id: '10',
    type: 'accelerator',
    name: 'Technoport',
    slug: 'technoport',
    tagline: 'Luxembourg\'s national innovation and startup hub',
    description: 'Technoport is Luxembourg\'s national incubator for innovative companies and startups. Located in Foetz, it offers co-working, labs, mentoring and access to its network.',
    website: 'https://technoport.lu',
    founded_year: 2010,
    city: 'Foetz',
    lat: 49.5300,
    lng: 6.0600,
    linkedin_url: 'https://linkedin.com/company/technoport',
    visible: true,
    featured: true,
    claimed: false,
    created_at: '2024-01-01',
  },
  {
    id: '11',
    type: 'accelerator',
    name: 'Lux Future Lab',
    slug: 'lux-future-lab',
    tagline: 'BIL\'s accelerator for early-stage fintech startups',
    description: 'Lux Future Lab is BIL Bank\'s accelerator programme, supporting fintech and adjacent startups with equity-free funding, mentorship and access to banking infrastructure.',
    website: 'https://luxfuturelab.lu',
    founded_year: 2016,
    city: 'Luxembourg City',
    lat: 49.6110,
    lng: 6.1290,
    visible: true,
    featured: false,
    claimed: false,
    created_at: '2024-01-01',
  },
  {
    id: '12',
    type: 'accelerator',
    name: 'nyuko',
    slug: 'nyuko',
    tagline: 'Supporting entrepreneurs from idea to market',
    description: 'nyuko is Luxembourg\'s centre for entrepreneurship, offering training, coaching and workspace to entrepreneurs at every stage of their journey.',
    website: 'https://nyuko.lu',
    founded_year: 2012,
    city: 'Luxembourg City',
    lat: 49.6090,
    lng: 6.1310,
    visible: true,
    featured: false,
    claimed: false,
    created_at: '2024-01-01',
  },
  {
    id: '13',
    type: 'service_provider',
    name: 'KPMG Luxembourg',
    slug: 'kpmg-luxembourg',
    tagline: 'Audit, tax and advisory for startups and funds',
    description: 'KPMG Luxembourg offers dedicated startup-friendly services including audit, tax structuring, fund administration and regulatory compliance for growth companies.',
    website: 'https://kpmg.com/lu',
    founded_year: 1966,
    city: 'Luxembourg City',
    lat: 49.6120,
    lng: 6.1330,
    visible: true,
    featured: false,
    claimed: false,
    created_at: '2024-01-01',
  },
  {
    id: '14',
    type: 'service_provider',
    name: 'Arendt & Medernach',
    slug: 'arendt-medernach',
    tagline: 'Leading law firm for tech and finance companies',
    description: 'Arendt & Medernach is Luxembourg\'s largest law firm, with a dedicated tech and innovation practice advising startups on legal structuring, IP and fundraising.',
    website: 'https://arendt.com',
    founded_year: 1988,
    city: 'Luxembourg City',
    lat: 49.6135,
    lng: 6.1295,
    visible: true,
    featured: false,
    claimed: false,
    created_at: '2024-01-01',
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    name: 'ICT Spring Europe 2025',
    slug: 'ict-spring-2025',
    description: 'Luxembourg\'s leading international tech and innovation conference bringing together 8,000+ attendees from across Europe and beyond.',
    start_date: '2025-06-12T09:00:00Z',
    end_date: '2025-06-13T18:00:00Z',
    location: 'European Convention Center Luxembourg',
    city: 'Luxembourg City',
    url: 'https://ictspring.com',
    type: 'conference',
    virtual: false,
    visible: true,
    created_at: '2024-01-01',
  },
  {
    id: 'e2',
    name: 'Startup Grind Luxembourg',
    slug: 'startup-grind-lu-june',
    description: 'Monthly fireside chat with inspiring founders and investors from the Luxembourg ecosystem. This month: scaling from Luxembourg to Europe.',
    start_date: '2025-07-03T18:30:00Z',
    end_date: '2025-07-03T21:00:00Z',
    location: 'Technoport, Foetz',
    city: 'Foetz',
    url: 'https://startupgrind.com/luxembourg',
    type: 'networking',
    virtual: false,
    visible: true,
    created_at: '2024-01-01',
  },
  {
    id: 'e3',
    name: 'Hack&Learn Hackathon — AI Edition',
    slug: 'hacklearn-ai-2025',
    description: 'A 48-hour hackathon focused on building AI-powered tools for the financial sector. Open to teams of 2–5, prizes up to €10,000.',
    start_date: '2025-07-19T09:00:00Z',
    end_date: '2025-07-20T18:00:00Z',
    location: 'Lux Future Lab',
    city: 'Luxembourg City',
    type: 'hackathon',
    virtual: false,
    visible: true,
    created_at: '2024-01-01',
  },
  {
    id: 'e4',
    name: 'Silicon Luxembourg Demo Day',
    slug: 'silicon-lu-demo-day-q3',
    description: 'Quarterly demo day where the best Luxembourg startups pitch to investors, corporates and the local tech community.',
    start_date: '2025-09-10T14:00:00Z',
    end_date: '2025-09-10T19:00:00Z',
    location: 'Rotondes, Luxembourg City',
    city: 'Luxembourg City',
    type: 'demo-day',
    virtual: false,
    visible: true,
    created_at: '2024-01-01',
  },
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'j1',
    entity_id: '1',
    title: 'Senior Backend Engineer',
    description: 'Join Talkwalker\'s engineering team to scale our data ingestion pipelines processing billions of social media posts.',
    location: 'Luxembourg City',
    remote: 'hybrid',
    type: 'full-time',
    url: 'https://talkwalker.com/careers',
    salary_min: 75000,
    salary_max: 95000,
    currency: 'EUR',
    posted_at: '2025-06-01T10:00:00Z',
    active: true,
    created_at: '2025-06-01',
    entity: MOCK_ENTITIES.find(e => e.id === '1'),
  },
  {
    id: 'j2',
    entity_id: '2',
    title: 'Robotics Software Engineer',
    description: 'Help us build the intelligence behind QTrobot — working on ROS2, motion planning and human-robot interaction algorithms.',
    location: 'Luxembourg City',
    remote: 'no',
    type: 'full-time',
    url: 'https://luxai.com/jobs',
    salary_min: 65000,
    salary_max: 85000,
    currency: 'EUR',
    posted_at: '2025-06-05T10:00:00Z',
    active: true,
    created_at: '2025-06-05',
    entity: MOCK_ENTITIES.find(e => e.id === '2'),
  },
  {
    id: 'j3',
    entity_id: '7',
    title: 'Venture Capital Analyst',
    description: 'Mangrove Capital is looking for an analyst to support deal sourcing, due diligence and portfolio management across our European investments.',
    location: 'Luxembourg City',
    remote: 'hybrid',
    type: 'full-time',
    salary_min: 55000,
    salary_max: 70000,
    currency: 'EUR',
    posted_at: '2025-06-08T10:00:00Z',
    active: true,
    created_at: '2025-06-08',
    entity: MOCK_ENTITIES.find(e => e.id === '7'),
  },
  {
    id: 'j4',
    entity_id: '5',
    title: 'Product Designer',
    description: 'Design delightful payment experiences for millions of users across Luxembourg and Benelux. Own end-to-end product design for new merchant features.',
    location: 'Luxembourg City',
    remote: 'hybrid',
    type: 'full-time',
    url: 'https://payconiq.com/careers',
    salary_min: 60000,
    salary_max: 80000,
    currency: 'EUR',
    posted_at: '2025-06-10T10:00:00Z',
    active: true,
    created_at: '2025-06-10',
    entity: MOCK_ENTITIES.find(e => e.id === '5'),
  },
  {
    id: 'j5',
    entity_id: '10',
    title: 'Startup Programme Manager',
    description: 'Support Technoport\'s resident startups by coordinating acceleration programmes, events and access to the EU funding ecosystem.',
    location: 'Foetz',
    remote: 'no',
    type: 'full-time',
    url: 'https://technoport.lu/jobs',
    salary_min: 45000,
    salary_max: 58000,
    currency: 'EUR',
    posted_at: '2025-06-12T10:00:00Z',
    active: true,
    created_at: '2025-06-12',
    entity: MOCK_ENTITIES.find(e => e.id === '10'),
  },
];

export const MOCK_FUNDING_ROUNDS = [
  { id: 'r1', startup_id: '1', round_type: 'Series A', amount: 3500000, currency: 'EUR', date: '2014-03-01', announced: true },
  { id: 'r2', startup_id: '1', round_type: 'Series B', amount: 6300000, currency: 'EUR', date: '2018-09-01', announced: true },
  { id: 'r3', startup_id: '3', round_type: 'Seed', amount: 2000000, currency: 'EUR', date: '2017-05-01', announced: true },
  { id: 'r4', startup_id: '3', round_type: 'Series A', amount: 5000000, currency: 'EUR', date: '2019-11-01', announced: true },
  { id: 'r5', startup_id: '3', round_type: 'Series B', amount: 7000000, currency: 'EUR', date: '2022-02-01', announced: true },
  { id: 'r6', startup_id: '5', round_type: 'Series A', amount: 15000000, currency: 'EUR', date: '2020-06-01', announced: true },
  { id: 'r7', startup_id: '5', round_type: 'Series B', amount: 30000000, currency: 'EUR', date: '2023-01-01', announced: true },
  { id: 'r8', startup_id: '2', round_type: 'Pre-seed', amount: 700000, currency: 'EUR', date: '2017-01-01', announced: true },
  { id: 'r9', startup_id: '2', round_type: 'Seed', amount: 1200000, currency: 'EUR', date: '2019-06-01', announced: true },
  { id: 'r10', startup_id: '2', round_type: 'Series A', amount: 1300000, currency: 'EUR', date: '2022-09-01', announced: true },
];

export const MOCK_ROUND_INVESTORS = [
  { id: 'ri1', round_id: 'r1', investor_id: '7', startup_id: '1', lead: true },
  { id: 'ri2', round_id: 'r2', investor_id: '7', startup_id: '1', lead: true },
  { id: 'ri3', round_id: 'r3', investor_id: '8', startup_id: '3', lead: true },
  { id: 'ri4', round_id: 'r4', investor_id: '8', startup_id: '3', lead: false },
  { id: 'ri5', round_id: 'r5', investor_id: '9', startup_id: '3', lead: true },
  { id: 'ri6', round_id: 'r6', investor_id: '9', startup_id: '5', lead: false },
  { id: 'ri7', round_id: 'r7', investor_id: '7', startup_id: '5', lead: false },
  { id: 'ri8', round_id: 'r8', investor_id: '8', startup_id: '2', lead: true },
  { id: 'ri9', round_id: 'r9', investor_id: '7', startup_id: '2', lead: false },
];

export const MOCK_TEAM_MEMBERS = [
  { id: 't1', entity_id: '1', name: 'Robert Glaesener', role: 'CEO', linkedin_url: 'https://linkedin.com/in/robertglaesener' },
  { id: 't2', entity_id: '1', name: 'Christophe Folschette', role: 'Co-founder & President', linkedin_url: 'https://linkedin.com/in/christophefolschette' },
  { id: 't3', entity_id: '1', name: 'Thibaut Britz', role: 'VP Engineering', linkedin_url: 'https://linkedin.com' },
  { id: 't4', entity_id: '2', name: 'Aghiles Adjali', role: 'CEO & Co-founder', linkedin_url: 'https://linkedin.com/in/aghilesadjali' },
  { id: 't5', entity_id: '2', name: 'Zowain Mimouna', role: 'CTO & Co-founder', linkedin_url: 'https://linkedin.com' },
  { id: 't6', entity_id: '3', name: 'Nicolas Cartier', role: 'CEO', linkedin_url: 'https://linkedin.com' },
  { id: 't7', entity_id: '3', name: 'Marie Bastos', role: 'COO', linkedin_url: 'https://linkedin.com' },
  { id: 't8', entity_id: '5', name: 'Nadalina Manaouil', role: 'CEO', linkedin_url: 'https://linkedin.com' },
  { id: 't9', entity_id: '5', name: 'Marc Hemmerling', role: 'CFO', linkedin_url: 'https://linkedin.com' },
  { id: 't10', entity_id: '7', name: 'Hans-Jürgen Schmitz', role: 'Managing Partner', linkedin_url: 'https://linkedin.com/in/hj-schmitz' },
  { id: 't11', entity_id: '7', name: 'Mark Tluszcz', role: 'Managing Partner', linkedin_url: 'https://linkedin.com/in/marktluszcz' },
  { id: 't12', entity_id: '7', name: 'Fabrice Dobremel', role: 'Partner', linkedin_url: 'https://linkedin.com' },
  { id: 't13', entity_id: '8', name: 'Jean-Michel Gaudron', role: 'Managing Partner', linkedin_url: 'https://linkedin.com' },
  { id: 't14', entity_id: '8', name: 'Marcus Feulner', role: 'Partner', linkedin_url: 'https://linkedin.com' },
  { id: 't15', entity_id: '9', name: 'Michèle Detaille', role: 'Board Member', linkedin_url: 'https://linkedin.com' },
  { id: 't16', entity_id: '9', name: 'Nicolas Buck', role: 'Managing Director', linkedin_url: 'https://linkedin.com' },
  { id: 't17', entity_id: '10', name: 'Stéphane Woynaroski', role: 'Director', linkedin_url: 'https://linkedin.com' },
  { id: 't18', entity_id: '12', name: 'Alice Bernard', role: 'General Manager', linkedin_url: 'https://linkedin.com' },
  { id: 't19', entity_id: '13', name: 'Laurent Goetz', role: 'Head of Startup Practice', linkedin_url: 'https://linkedin.com' },
  { id: 't20', entity_id: '14', name: 'Gilles Dusemon', role: 'Partner, Tech & Innovation', linkedin_url: 'https://linkedin.com' },
];
